version: '3'
services:
  mean-mongo:
    image: mongo
    volumes:
      - ./database:/data/db
    ports: 
      - 27017:27017
  mean-stack:
    build: ./app
    ports:
      - 80:3000
    depends_on:
      - mean-mongo
